'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BancoSebastianLetona.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Airbus_Autopilot_Off_da5260f2_67ba_4a3b_aaf7_7acba8c49577() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Airbus_Autopilot_Off_da5260f2_67ba_4a3b_aaf7_7acba8c49577", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anímate_a_conocer_algunos_rincones_del_centro_histórico_de_la_Ciudad_de_Guatemala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anímate_a_conocer_algunos_rincones_del_centro_histórico_de_la_Ciudad_de_Guatemala"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bojack_horseman_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bojack_horseman_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bolsa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bolsa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Bus_8_Start_ffca03f4_0f1c_3689_80df_486d84a48aa8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bus_8_Start_ffca03f4_0f1c_3689_80df_486d84a48aa8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Creaking_Boat_Sms_14dc17c8_aa91_31d2_b025_bdbd82b33072() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Creaking_Boat_Sms_14dc17c8_aa91_31d2_b025_bdbd82b33072", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cupon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cupon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Dice_Roll_064fcfd5_b570_3f22_9b53_5b126d2b0925() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Dice_Roll_064fcfd5_b570_3f22_9b53_5b126d2b0925", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Electric_Shock_257ec604_ec64_3255_981b_bf2d607a7e36() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Electric_Shock_257ec604_ec64_3255_981b_bf2d607a7e36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property error_text_message() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("error_text_message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property golden_time_sad_song() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("golden_time_sad_song", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Money_e79c530c_1f53_4c93_bf78_c27b0ce181f5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Money_e79c530c_1f53_4c93_bf78_c27b0ce181f5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MOUSE_CLICK() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MOUSE_CLICK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nep_Nep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nep_Nep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OBI_WAN_HELLO_THERE() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OBI_WAN_HELLO_THERE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OOF() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OOF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Train_Horn_8f4e4fb0_3b0a_48b2_bdb6_50cbd71b7900() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Train_Horn_8f4e4fb0_3b0a_48b2_bdb6_50cbd71b7900", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Water_c461fc80_d814_316a_82dc_7f2fbd1d2406() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Water_c461fc80_d814_316a_82dc_7f2fbd1d2406", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
